version: '3'

volumes:
  postgres:
  redis:
  meilisearch:

services:
  postgres:
    image: postgres:11.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data
    network_mode: host

  redis:
    image: redis:5.0.4-alpine
    network_mode: host
  
  mailhog:
    image: mailhog/mailhog:v1.0.1
    network_mode: host
    environment:
      MH_HOSTNAME: mailhog.example

  meilisearch:
    image: getmeili/meilisearch:v0.20.0
    command: ./meilisearch --no-analytics=true
    network_mode: host
    volumes:
      - meilisearch:/data.ms
